os:
  - linux
language: node_js
node_js:
  - '8'

script:
  - npm install
  - node like.js
  - node follow.js
  - node unfollow.js

notifications:
  email: false
  slack:
    secure: "KwoeIL3Gj0Hm3UHehlir2NiEM02yI+OiBMwqy77Yuzr6K76QP+NvmBoh6gKC/vs9VFMjw9ai6cCCjPKPyGJVTP1WxOjQfgUJ6+uBw6uHa7tAYw0DzT0I31OvdAlcGcnvGLhsUCctYGkUNVJ1nzLhbVZnCU4cMHWaZEVEd122TNHTDmyfoHNKzhvTTabtpa0v9hGQ9eDrfFCquL6xJkdIFL7PHBo1uYIv+gv0BgqgHGNza6iMXIIZwJ4ObsdlOY95Dl5UzHX8cZItFJiTWdX/3DH0ecdVdQ972/sfXnAqYaTKr+PfGjPqgWpGN0CeGWVyKAxOpJ/9Sfx6ImMnv87gC1mbZ+CBCxDqie9bvrziLIlym13J24K4YsMdvYzXSClv0Am3ooOtckH9yp4rzFo/zHUFUJaqWFvjBOidAkUNq3h28UujBSdaD9THZpo/cK6TlQxc/Kgn3u5u2/1HsKAEz/CiA9W0srxzVpKCmRYKSxBBIAlEVH6/VRE+TQD/4hEeOt2KewxFNE7owROc8iQQ9hqIVVQEIVmI9ckbKo7Yt5sqdITTYU+p4mKsgXvkg+PEXpxKsCyWjas/8tjmUL8hxLRUfsP2VjkFwEtChO5tVPxwVNwtnolE2lU/tRs9iV7PVMGxGBwypUPhVmtmSQ4vc+isuoPIStwDeqFX6Nyvntg="